"use client";

import { useRef, useState } from "react";

const FPS = 25;
const N_FRAMES = 50;
const RATES = [0.25, 0.5, 1, 2, 4];

/** FpsLab (Module 39.1): the real sample-ball-25fps.mp4 clip (25 fps, 50 frames, generated by
 *  assets/videos/generate_videos.py) in an HTML5 <video>, with frame-accurate stepping
 *  (currentTime +/- 1/fps) and a playback-rate control, so fps -> real time -> frame index
 *  is something the reader can click through rather than just read as a formula. */
export function FpsLab({ caption }: { caption?: string }) {
  const ref = useRef<HTMLVideoElement>(null);
  const [time, setTime] = useState(0);
  const [rate, setRate] = useState(1);
  const [playing, setPlaying] = useState(false);

  const frameIndex = Math.min(N_FRAMES - 1, Math.round(time * FPS));

  const step = (delta: number) => {
    const v = ref.current;
    if (!v) return;
    const next = Math.max(0, Math.min((N_FRAMES - 1) / FPS, v.currentTime + delta / FPS));
    v.currentTime = next;
    setTime(next);
  };

  const setPlaybackRate = (r: number) => {
    setRate(r);
    if (ref.current) ref.current.playbackRate = r;
  };

  const togglePlay = () => {
    const v = ref.current;
    if (!v) return;
    if (v.paused) { v.play(); setPlaying(true); } else { v.pause(); setPlaying(false); }
  };

  return (
    <figure className="fig fpslab">
      <video
        ref={ref}
        src="/videos/sample-ball-25fps.mp4"
        onTimeUpdate={(e) => setTime(e.currentTarget.currentTime)}
        onEnded={() => setPlaying(false)}
        muted
        playsInline
        style={{ width: "100%", maxWidth: 400, display: "block", borderRadius: "var(--radius)" }}
      />
      <div className="sc-ctl" style={{ marginTop: "0.6rem" }}>
        <button type="button" onClick={togglePlay}>{playing ? "Pause" : "Play"}</button>
        <button type="button" onClick={() => step(-1)}>&larr; 1 frame</button>
        <button type="button" onClick={() => step(1)}>1 frame &rarr;</button>
        <label className="ctl ctl-wide"><span>Playback rate <output>{rate}&times;</output></span>
          <input type="range" min={0} max={RATES.length - 1} step={1} value={RATES.indexOf(rate)}
            onChange={(e) => setPlaybackRate(RATES[Number(e.target.value)])} aria-label="Playback rate" />
        </label>
      </div>
      <ul className="ap-stats">
        <li><span>Current time</span><strong>{time.toFixed(3)} s</strong><em>read from the video element</em></li>
        <li><span>Frame index</span><strong>{frameIndex} / {N_FRAMES - 1}</strong><em>round(time &times; {FPS} fps)</em></li>
        <li><span>Declared fps</span><strong>{FPS}</strong><em>50 frames &divide; 25 fps = 2.000 s total</em></li>
      </ul>
      <div className="pg-readout"><span>Stepping one frame moves the clock by exactly 1/{FPS} s = {(1000 / FPS).toFixed(0)} ms — the same spacing `cv2.VideoCapture`&apos;s `CAP_PROP_POS_MSEC` reports for this file (Section 3). Playback rate changes how fast time passes here, never what a frame index means.</span></div>
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}
