/** Generated by running each case on opencv-python-headless 4.13.0.92 (Chapter 8.3). Key: function|dtype|shape|layout.
 *  Value: [1, result] or [0, error message, hint key]. Do not edit by hand. */
export const BINDING_RESULTS: Record<string, [number, string, string?]> = {
"cvtColor BGR→GRAY|uint8|(h, w)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint8|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint8|(h, w)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint8|(h, w, 1)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint8|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint8|(h, w, 1)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint8|(h, w, 3)|contiguous": [
1,
"(6, 8) uint8"
],
"cvtColor BGR→GRAY|uint8|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"cvtColor BGR→GRAY|uint8|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"cvtColor BGR→GRAY|uint8|(h, w, 4)|contiguous": [
1,
"(6, 8) uint8"
],
"cvtColor BGR→GRAY|uint8|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"cvtColor BGR→GRAY|uint8|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"cvtColor BGR→GRAY|int8|(h, w)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int8|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int8|(h, w)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int8|(h, w, 1)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int8|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int8|(h, w, 1)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int8|(h, w, 3)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 1 (CV_8S))",
"depth"
],
"cvtColor BGR→GRAY|int8|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 1 (CV_8S))",
"depth"
],
"cvtColor BGR→GRAY|int8|(h, w, 3)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 1 (CV_8S))",
"depth"
],
"cvtColor BGR→GRAY|int8|(h, w, 4)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 1 (CV_8S))",
"depth"
],
"cvtColor BGR→GRAY|int8|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 1 (CV_8S))",
"depth"
],
"cvtColor BGR→GRAY|int8|(h, w, 4)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 1 (CV_8S))",
"depth"
],
"cvtColor BGR→GRAY|uint16|(h, w)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint16|(h, w)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint16|(h, w, 1)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint16|(h, w, 1)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|uint16|(h, w, 3)|contiguous": [
1,
"(6, 8) uint16"
],
"cvtColor BGR→GRAY|uint16|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint16"
],
"cvtColor BGR→GRAY|uint16|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8) uint16"
],
"cvtColor BGR→GRAY|uint16|(h, w, 4)|contiguous": [
1,
"(6, 8) uint16"
],
"cvtColor BGR→GRAY|uint16|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint16"
],
"cvtColor BGR→GRAY|uint16|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8) uint16"
],
"cvtColor BGR→GRAY|int16|(h, w)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int16|(h, w)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int16|(h, w, 1)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int16|(h, w, 1)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int16|(h, w, 3)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 3 (CV_16S))",
"depth"
],
"cvtColor BGR→GRAY|int16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 3 (CV_16S))",
"depth"
],
"cvtColor BGR→GRAY|int16|(h, w, 3)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 3 (CV_16S))",
"depth"
],
"cvtColor BGR→GRAY|int16|(h, w, 4)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 3 (CV_16S))",
"depth"
],
"cvtColor BGR→GRAY|int16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 3 (CV_16S))",
"depth"
],
"cvtColor BGR→GRAY|int16|(h, w, 4)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 3 (CV_16S))",
"depth"
],
"cvtColor BGR→GRAY|int32|(h, w)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int32|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int32|(h, w)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int32|(h, w, 1)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int32|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int32|(h, w, 1)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int32|(h, w, 3)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int32|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int32|(h, w, 3)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int32|(h, w, 4)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int32|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int32|(h, w, 4)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|float16|(h, w)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float16|(h, w)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float16|(h, w, 1)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float16|(h, w, 1)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float16|(h, w, 3)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 7 (CV_16F))",
"depth"
],
"cvtColor BGR→GRAY|float16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 7 (CV_16F))",
"depth"
],
"cvtColor BGR→GRAY|float16|(h, w, 3)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 7 (CV_16F))",
"depth"
],
"cvtColor BGR→GRAY|float16|(h, w, 4)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 7 (CV_16F))",
"depth"
],
"cvtColor BGR→GRAY|float16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 7 (CV_16F))",
"depth"
],
"cvtColor BGR→GRAY|float16|(h, w, 4)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 7 (CV_16F))",
"depth"
],
"cvtColor BGR→GRAY|float32|(h, w)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float32|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float32|(h, w)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float32|(h, w, 1)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float32|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float32|(h, w, 1)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float32|(h, w, 3)|contiguous": [
1,
"(6, 8) float32"
],
"cvtColor BGR→GRAY|float32|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float32"
],
"cvtColor BGR→GRAY|float32|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8) float32"
],
"cvtColor BGR→GRAY|float32|(h, w, 4)|contiguous": [
1,
"(6, 8) float32"
],
"cvtColor BGR→GRAY|float32|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float32"
],
"cvtColor BGR→GRAY|float32|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8) float32"
],
"cvtColor BGR→GRAY|float64|(h, w)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float64|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float64|(h, w)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float64|(h, w, 1)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float64|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float64|(h, w, 1)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|float64|(h, w, 3)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 6 (CV_64F))",
"depth"
],
"cvtColor BGR→GRAY|float64|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 6 (CV_64F))",
"depth"
],
"cvtColor BGR→GRAY|float64|(h, w, 3)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 6 (CV_64F))",
"depth"
],
"cvtColor BGR→GRAY|float64|(h, w, 4)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 6 (CV_64F))",
"depth"
],
"cvtColor BGR→GRAY|float64|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 6 (CV_64F))",
"depth"
],
"cvtColor BGR→GRAY|float64|(h, w, 4)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 6 (CV_64F))",
"depth"
],
"cvtColor BGR→GRAY|int64|(h, w)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int64|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int64|(h, w)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int64|(h, w, 1)|contiguous": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int64|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int64|(h, w, 1)|transposed (a.T)": [
0,
"(-15:Bad number of channels) in function 'cvtColor': Invalid number of channels in input image (scn is 1)",
"channels"
],
"cvtColor BGR→GRAY|int64|(h, w, 3)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int64|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int64|(h, w, 3)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int64|(h, w, 4)|contiguous": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int64|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|int64|(h, w, 4)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'cvtColor': Unsupported depth of input image (depth is 4 (CV_32S))",
"depth"
],
"cvtColor BGR→GRAY|bool|(h, w)|contiguous": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w, 1)|contiguous": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w, 3)|contiguous": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w, 4)|contiguous": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"cvtColor BGR→GRAY|bool|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'cvtColor': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|uint8|(h, w)|contiguous": [
1,
"(6, 8) uint8"
],
"GaussianBlur 3×3|uint8|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"GaussianBlur 3×3|uint8|(h, w)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"GaussianBlur 3×3|uint8|(h, w, 1)|contiguous": [
1,
"(6, 8) uint8"
],
"GaussianBlur 3×3|uint8|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"GaussianBlur 3×3|uint8|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"GaussianBlur 3×3|uint8|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) uint8"
],
"GaussianBlur 3×3|uint8|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) uint8"
],
"GaussianBlur 3×3|uint8|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) uint8"
],
"GaussianBlur 3×3|uint8|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) uint8"
],
"GaussianBlur 3×3|uint8|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) uint8"
],
"GaussianBlur 3×3|uint8|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) uint8"
],
"GaussianBlur 3×3|int8|(h, w)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=1), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=1), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=1), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w, 1)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=1), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=1), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w, 1)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=1), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w, 3)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=17), and buffer format (=21) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=17), and buffer format (=21) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w, 3)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=17), and buffer format (=21) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w, 4)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=25), and buffer format (=29) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=25), and buffer format (=29) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int8|(h, w, 4)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=25), and buffer format (=29) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|uint16|(h, w)|contiguous": [
1,
"(6, 8) uint16"
],
"GaussianBlur 3×3|uint16|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint16"
],
"GaussianBlur 3×3|uint16|(h, w)|transposed (a.T)": [
1,
"(6, 8) uint16"
],
"GaussianBlur 3×3|uint16|(h, w, 1)|contiguous": [
1,
"(6, 8) uint16"
],
"GaussianBlur 3×3|uint16|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint16"
],
"GaussianBlur 3×3|uint16|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) uint16"
],
"GaussianBlur 3×3|uint16|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) uint16"
],
"GaussianBlur 3×3|uint16|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) uint16"
],
"GaussianBlur 3×3|uint16|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) uint16"
],
"GaussianBlur 3×3|uint16|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) uint16"
],
"GaussianBlur 3×3|uint16|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) uint16"
],
"GaussianBlur 3×3|uint16|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) uint16"
],
"GaussianBlur 3×3|int16|(h, w)|contiguous": [
1,
"(6, 8) int16"
],
"GaussianBlur 3×3|int16|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) int16"
],
"GaussianBlur 3×3|int16|(h, w)|transposed (a.T)": [
1,
"(6, 8) int16"
],
"GaussianBlur 3×3|int16|(h, w, 1)|contiguous": [
1,
"(6, 8) int16"
],
"GaussianBlur 3×3|int16|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) int16"
],
"GaussianBlur 3×3|int16|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) int16"
],
"GaussianBlur 3×3|int16|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) int16"
],
"GaussianBlur 3×3|int16|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) int16"
],
"GaussianBlur 3×3|int16|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) int16"
],
"GaussianBlur 3×3|int16|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) int16"
],
"GaussianBlur 3×3|int16|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) int16"
],
"GaussianBlur 3×3|int16|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) int16"
],
"GaussianBlur 3×3|int32|(h, w)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w, 1)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w, 1)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w, 3)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=20), and buffer format (=21) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=20), and buffer format (=21) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w, 3)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=20), and buffer format (=21) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w, 4)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=28), and buffer format (=29) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=28), and buffer format (=29) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int32|(h, w, 4)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=28), and buffer format (=29) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|float16|(h, w)|contiguous": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w, 1)|contiguous": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w, 1)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w, 3)|contiguous": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w, 3)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w, 4)|contiguous": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float16|(h, w, 4)|transposed (a.T)": [
0,
"(-2:Unspecified error) in function 'getGaussianKernel': ktype must be CV_32F or CV_64F",
"depth"
],
"GaussianBlur 3×3|float32|(h, w)|contiguous": [
1,
"(6, 8) float32"
],
"GaussianBlur 3×3|float32|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float32"
],
"GaussianBlur 3×3|float32|(h, w)|transposed (a.T)": [
1,
"(6, 8) float32"
],
"GaussianBlur 3×3|float32|(h, w, 1)|contiguous": [
1,
"(6, 8) float32"
],
"GaussianBlur 3×3|float32|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float32"
],
"GaussianBlur 3×3|float32|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) float32"
],
"GaussianBlur 3×3|float32|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) float32"
],
"GaussianBlur 3×3|float32|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) float32"
],
"GaussianBlur 3×3|float32|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) float32"
],
"GaussianBlur 3×3|float32|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) float32"
],
"GaussianBlur 3×3|float32|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) float32"
],
"GaussianBlur 3×3|float32|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) float32"
],
"GaussianBlur 3×3|float64|(h, w)|contiguous": [
1,
"(6, 8) float64"
],
"GaussianBlur 3×3|float64|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float64"
],
"GaussianBlur 3×3|float64|(h, w)|transposed (a.T)": [
1,
"(6, 8) float64"
],
"GaussianBlur 3×3|float64|(h, w, 1)|contiguous": [
1,
"(6, 8) float64"
],
"GaussianBlur 3×3|float64|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float64"
],
"GaussianBlur 3×3|float64|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) float64"
],
"GaussianBlur 3×3|float64|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) float64"
],
"GaussianBlur 3×3|float64|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) float64"
],
"GaussianBlur 3×3|float64|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) float64"
],
"GaussianBlur 3×3|float64|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) float64"
],
"GaussianBlur 3×3|float64|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) float64"
],
"GaussianBlur 3×3|float64|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) float64"
],
"GaussianBlur 3×3|int64|(h, w)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"int64in"
],
"GaussianBlur 3×3|int64|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"int64in"
],
"GaussianBlur 3×3|int64|(h, w)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"int64in"
],
"GaussianBlur 3×3|int64|(h, w, 1)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"int64in"
],
"GaussianBlur 3×3|int64|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"int64in"
],
"GaussianBlur 3×3|int64|(h, w, 1)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'",
"int64in"
],
"GaussianBlur 3×3|int64|(h, w, 3)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=20), and buffer format (=21) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int64|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=20), and buffer format (=21) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int64|(h, w, 3)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=20), and buffer format (=21) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int64|(h, w, 4)|contiguous": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=28), and buffer format (=29) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int64|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=28), and buffer format (=29) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|int64|(h, w, 4)|transposed (a.T)": [
0,
"(-213:The function/feature is not implemented) Unsupported combination of source format (=28), and buffer format (=29) in function 'getLinearRowFilter'",
"depth"
],
"GaussianBlur 3×3|bool|(h, w)|contiguous": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w, 1)|contiguous": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w, 3)|contiguous": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w, 4)|contiguous": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"GaussianBlur 3×3|bool|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'GaussianBlur': src data type = bool is not supported",
"bool"
],
"threshold 100|uint8|(h, w)|contiguous": [
1,
"(6, 8) uint8"
],
"threshold 100|uint8|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"threshold 100|uint8|(h, w)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"threshold 100|uint8|(h, w, 1)|contiguous": [
1,
"(6, 8) uint8"
],
"threshold 100|uint8|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"threshold 100|uint8|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"threshold 100|uint8|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) uint8"
],
"threshold 100|uint8|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) uint8"
],
"threshold 100|uint8|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) uint8"
],
"threshold 100|uint8|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) uint8"
],
"threshold 100|uint8|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) uint8"
],
"threshold 100|uint8|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) uint8"
],
"threshold 100|int8|(h, w)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w, 1)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w, 1)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w, 3)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w, 3)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w, 4)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int8|(h, w, 4)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|uint16|(h, w)|contiguous": [
1,
"(6, 8) uint16"
],
"threshold 100|uint16|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint16"
],
"threshold 100|uint16|(h, w)|transposed (a.T)": [
1,
"(6, 8) uint16"
],
"threshold 100|uint16|(h, w, 1)|contiguous": [
1,
"(6, 8) uint16"
],
"threshold 100|uint16|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint16"
],
"threshold 100|uint16|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) uint16"
],
"threshold 100|uint16|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) uint16"
],
"threshold 100|uint16|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) uint16"
],
"threshold 100|uint16|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) uint16"
],
"threshold 100|uint16|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) uint16"
],
"threshold 100|uint16|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) uint16"
],
"threshold 100|uint16|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) uint16"
],
"threshold 100|int16|(h, w)|contiguous": [
1,
"(6, 8) int16"
],
"threshold 100|int16|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) int16"
],
"threshold 100|int16|(h, w)|transposed (a.T)": [
1,
"(6, 8) int16"
],
"threshold 100|int16|(h, w, 1)|contiguous": [
1,
"(6, 8) int16"
],
"threshold 100|int16|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) int16"
],
"threshold 100|int16|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) int16"
],
"threshold 100|int16|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) int16"
],
"threshold 100|int16|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) int16"
],
"threshold 100|int16|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) int16"
],
"threshold 100|int16|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) int16"
],
"threshold 100|int16|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) int16"
],
"threshold 100|int16|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) int16"
],
"threshold 100|int32|(h, w)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w, 1)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w, 1)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w, 3)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w, 3)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w, 4)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int32|(h, w, 4)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w, 1)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w, 1)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w, 3)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w, 3)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w, 4)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float16|(h, w, 4)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|float32|(h, w)|contiguous": [
1,
"(6, 8) float32"
],
"threshold 100|float32|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float32"
],
"threshold 100|float32|(h, w)|transposed (a.T)": [
1,
"(6, 8) float32"
],
"threshold 100|float32|(h, w, 1)|contiguous": [
1,
"(6, 8) float32"
],
"threshold 100|float32|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float32"
],
"threshold 100|float32|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) float32"
],
"threshold 100|float32|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) float32"
],
"threshold 100|float32|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) float32"
],
"threshold 100|float32|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) float32"
],
"threshold 100|float32|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) float32"
],
"threshold 100|float32|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) float32"
],
"threshold 100|float32|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) float32"
],
"threshold 100|float64|(h, w)|contiguous": [
1,
"(6, 8) float64"
],
"threshold 100|float64|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float64"
],
"threshold 100|float64|(h, w)|transposed (a.T)": [
1,
"(6, 8) float64"
],
"threshold 100|float64|(h, w, 1)|contiguous": [
1,
"(6, 8) float64"
],
"threshold 100|float64|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) float64"
],
"threshold 100|float64|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) float64"
],
"threshold 100|float64|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) float64"
],
"threshold 100|float64|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 3) float64"
],
"threshold 100|float64|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8, 3) float64"
],
"threshold 100|float64|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) float64"
],
"threshold 100|float64|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8, 4) float64"
],
"threshold 100|float64|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8, 4) float64"
],
"threshold 100|int64|(h, w)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w, 1)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w, 1)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w, 3)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w, 3)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w, 4)|contiguous": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|int64|(h, w, 4)|transposed (a.T)": [
0,
"(-210:Unsupported format or combination of formats)  in function 'threshold'",
"depth"
],
"threshold 100|bool|(h, w)|contiguous": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w, 1)|contiguous": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w, 3)|contiguous": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w, 4)|contiguous": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"threshold 100|bool|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'threshold': src data type = bool is not supported",
"bool"
],
"Canny|uint8|(h, w)|contiguous": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w, 1)|contiguous": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w, 1)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w, 1)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w, 3)|contiguous": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w, 3)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w, 3)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w, 4)|contiguous": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w, 4)|every 2nd column (a[:, ::2])": [
1,
"(6, 8) uint8"
],
"Canny|uint8|(h, w, 4)|transposed (a.T)": [
1,
"(6, 8) uint8"
],
"Canny|int8|(h, w)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w, 1)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w, 1)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w, 3)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w, 3)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w, 4)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int8|(h, w, 4)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w, 1)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w, 1)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w, 3)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w, 3)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w, 4)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|uint16|(h, w, 4)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w, 1)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w, 1)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w, 3)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w, 3)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w, 4)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int16|(h, w, 4)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w, 1)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w, 1)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w, 3)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w, 3)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w, 4)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int32|(h, w, 4)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w, 1)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w, 1)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w, 3)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w, 3)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w, 4)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float16|(h, w, 4)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w, 1)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w, 1)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w, 3)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w, 3)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w, 4)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float32|(h, w, 4)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w, 1)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w, 1)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w, 3)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w, 3)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w, 4)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|float64|(h, w, 4)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w, 1)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w, 1)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w, 3)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w, 3)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w, 4)|contiguous": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|int64|(h, w, 4)|transposed (a.T)": [
0,
"(-215:Assertion failed) _src.depth() == CV_8U in function 'Canny'",
"depth"
],
"Canny|bool|(h, w)|contiguous": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w, 1)|contiguous": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w, 3)|contiguous": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w, 4)|contiguous": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"Canny|bool|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'Canny': image data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|uint8|(h, w)|contiguous": [
1,
"(6, 8) uint8 (same array, drawn in place)"
],
"rectangle (draws in place)|uint8|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint8|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint8|(h, w, 1)|contiguous": [
1,
"(6, 8, 1) uint8 (same array, drawn in place)"
],
"rectangle (draws in place)|uint8|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint8|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint8|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) uint8 (same array, drawn in place)"
],
"rectangle (draws in place)|uint8|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint8|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint8|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) uint8 (same array, drawn in place)"
],
"rectangle (draws in place)|uint8|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint8|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int8|(h, w)|contiguous": [
1,
"(6, 8) int8 (same array, drawn in place)"
],
"rectangle (draws in place)|int8|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int8|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int8|(h, w, 1)|contiguous": [
1,
"(6, 8, 1) int8 (same array, drawn in place)"
],
"rectangle (draws in place)|int8|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int8|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int8|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) int8 (same array, drawn in place)"
],
"rectangle (draws in place)|int8|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int8|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int8|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) int8 (same array, drawn in place)"
],
"rectangle (draws in place)|int8|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int8|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint16|(h, w)|contiguous": [
1,
"(6, 8) uint16 (same array, drawn in place)"
],
"rectangle (draws in place)|uint16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint16|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint16|(h, w, 1)|contiguous": [
1,
"(6, 8, 1) uint16 (same array, drawn in place)"
],
"rectangle (draws in place)|uint16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint16|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint16|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) uint16 (same array, drawn in place)"
],
"rectangle (draws in place)|uint16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint16|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint16|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) uint16 (same array, drawn in place)"
],
"rectangle (draws in place)|uint16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|uint16|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int16|(h, w)|contiguous": [
1,
"(6, 8) int16 (same array, drawn in place)"
],
"rectangle (draws in place)|int16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int16|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int16|(h, w, 1)|contiguous": [
1,
"(6, 8, 1) int16 (same array, drawn in place)"
],
"rectangle (draws in place)|int16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int16|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int16|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) int16 (same array, drawn in place)"
],
"rectangle (draws in place)|int16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int16|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int16|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) int16 (same array, drawn in place)"
],
"rectangle (draws in place)|int16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int16|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int32|(h, w)|contiguous": [
1,
"(6, 8) int32 (same array, drawn in place)"
],
"rectangle (draws in place)|int32|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int32|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int32|(h, w, 1)|contiguous": [
1,
"(6, 8, 1) int32 (same array, drawn in place)"
],
"rectangle (draws in place)|int32|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int32|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int32|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) int32 (same array, drawn in place)"
],
"rectangle (draws in place)|int32|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int32|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int32|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) int32 (same array, drawn in place)"
],
"rectangle (draws in place)|int32|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int32|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float16|(h, w)|contiguous": [
1,
"(6, 8) float16 (same array, drawn in place)"
],
"rectangle (draws in place)|float16|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float16|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float16|(h, w, 1)|contiguous": [
1,
"(6, 8, 1) float16 (same array, drawn in place)"
],
"rectangle (draws in place)|float16|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float16|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float16|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) float16 (same array, drawn in place)"
],
"rectangle (draws in place)|float16|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float16|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float16|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) float16 (same array, drawn in place)"
],
"rectangle (draws in place)|float16|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float16|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float32|(h, w)|contiguous": [
1,
"(6, 8) float32 (same array, drawn in place)"
],
"rectangle (draws in place)|float32|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float32|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float32|(h, w, 1)|contiguous": [
1,
"(6, 8, 1) float32 (same array, drawn in place)"
],
"rectangle (draws in place)|float32|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float32|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float32|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) float32 (same array, drawn in place)"
],
"rectangle (draws in place)|float32|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float32|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float32|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) float32 (same array, drawn in place)"
],
"rectangle (draws in place)|float32|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float32|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float64|(h, w)|contiguous": [
1,
"(6, 8) float64 (same array, drawn in place)"
],
"rectangle (draws in place)|float64|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float64|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float64|(h, w, 1)|contiguous": [
1,
"(6, 8, 1) float64 (same array, drawn in place)"
],
"rectangle (draws in place)|float64|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float64|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float64|(h, w, 3)|contiguous": [
1,
"(6, 8, 3) float64 (same array, drawn in place)"
],
"rectangle (draws in place)|float64|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float64|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float64|(h, w, 4)|contiguous": [
1,
"(6, 8, 4) float64 (same array, drawn in place)"
],
"rectangle (draws in place)|float64|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|float64|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"layout"
],
"rectangle (draws in place)|int64|(h, w)|contiguous": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w, 1)|contiguous": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w, 3)|contiguous": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w, 4)|contiguous": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|int64|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': Layout of the output array img is incompatible with cv::Mat",
"int64out"
],
"rectangle (draws in place)|bool|(h, w)|contiguous": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w, 1)|contiguous": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w, 1)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w, 1)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w, 3)|contiguous": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w, 3)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w, 3)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w, 4)|contiguous": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w, 4)|every 2nd column (a[:, ::2])": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
],
"rectangle (draws in place)|bool|(h, w, 4)|transposed (a.T)": [
0,
"(-5:Bad argument) in function 'rectangle': img data type = bool is not supported",
"bool"
]
};
